title: "Dapy: Distributed Algorithm Simulator"
description: "Simulate, prototype, and visualize distributed algorithms."
logo: "/dapy/assets/logo/dapy-logo.svg"
baseurl: "/dapy"

# Theme
remote_theme: just-the-docs/just-the-docs

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

# Kramdown configuration with syntax highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

# Just the Docs configuration
search_enabled: true
aux_links:
  "GitHub": https://github.com/xdefago/dapy
